= jPBE - do as I showed

This is the open source, java implementation of my https://selman.li/thesis[bachelor thesis].

== Abstract
Millions of people need to analyze raw data of varying quality to support their job function. 
In a lot of cases the present data needs to be refined and  rocessed from its raw form to a more structured format in 
order to analyze and visualize it. 
This process is time-intensive and error-prone. 
Usually tools like Microsoft Excel or OpenRefine are used to improve that process. 
However, any nontrivial data wrangling task remains inaccessible to non-programmers. 
Furthermore, existing tools only cover the most common use cases, i.e. they are business agnostic.

Programming by example (PBE), a subfield of program synthesis, allows for a natural and intuitive user 
interaction mechanism. 
Users can specify their intent by providing input output examples for string transformations.

Using PBE for data wrangling is not a novel idea. 
Flash Fill is a PBE feature in Excel and Microsoft’s PROSE framework shows the potential of PBE for data wrangling. 
However, these existing solutions cannot be integrated into custom software.

Therefore, we developed a custom PBE system for data wrangling tasks. 
We describe a custom domain-specific language (DSL) for complex string manipulations. 
We present a data structure to represent a large number of programs built in our DSL. 
We introduce a custom synthesis algorithm that populates our data structure with programs to transform string inputs 
to their intended outputs.
