/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package li.selman.jpbe;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.*;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertThat(classUnderTest.someLibraryMethod()).as("someLibraryMethod should return 'true'").isTrue();
    }
}
